import type {
  ActivityEvent,
  AppNotification,
  AutomationAgent,
  AutomationStats,
  CandidateEmail,
  FollowUpRule,
  InterviewEvaluationResult,
  InterviewReminder,
  OfferLetter,
  ScheduleSuggestion,
} from "@/types/automation";

export const MOCK_EMAILS: CandidateEmail[] = [
  {
    id: "em-1",
    candidateId: "c1",
    candidateName: "Emily Johnson",
    event: "Resume Received",
    subject: "We received your application — TalentPilot Labs",
    body: `Dear Emily,\n\nThank you for applying to the Junior Frontend Developer role. Our team has received your resume and will review it shortly.\n\nBest regards,\nTalent Acquisition`,
    status: "Sent",
    createdAt: "2026-07-18T09:21:00Z",
    sentAt: "2026-07-18T09:21:00Z",
  },
  {
    id: "em-2",
    candidateId: "c1",
    candidateName: "Emily Johnson",
    event: "Interview Invitation",
    subject: "Interview Invitation — Junior Frontend Developer",
    body: `Dear Emily,\n\nWe'd love to invite you to a 45-minute interview. Please reply with your availability this week.\n\nBest regards,\nTalent Acquisition`,
    status: "Sent",
    createdAt: "2026-07-18T10:12:00Z",
    sentAt: "2026-07-18T10:12:00Z",
  },
  {
    id: "em-3",
    candidateId: "c2",
    candidateName: "Marcus Chen",
    event: "Interview Invitation",
    subject: "Interview Invitation — Frontend Developer",
    body: `Dear Marcus,\n\nThank you for your interest. We would like to schedule a technical interview.\n\nBest regards,\nTalent Acquisition`,
    status: "Scheduled",
    createdAt: "2026-07-18T11:00:00Z",
    scheduledAt: "2026-07-18T14:00:00Z",
  },
  {
    id: "em-4",
    candidateId: "c8",
    candidateName: "Noah Williams",
    event: "Rejection",
    subject: "Update on your application",
    body: `Dear Noah,\n\nThank you for interviewing with us. After careful consideration, we have decided to move forward with other candidates. We appreciate your time and encourage you to apply again in the future.\n\nKind regards,\nTalent Acquisition`,
    status: "Pending",
    createdAt: "2026-07-18T12:00:00Z",
  },
];

export const MOCK_REMINDERS: InterviewReminder[] = [
  {
    id: "rm-1",
    candidateName: "Emily Johnson",
    interviewAt: "2026-07-19T10:00:00Z",
    offsetLabel: "24 hours",
    status: "Sent",
    channel: "Email",
  },
  {
    id: "rm-2",
    candidateName: "Emily Johnson",
    interviewAt: "2026-07-19T10:00:00Z",
    offsetLabel: "1 hour",
    status: "Upcoming",
    channel: "Email",
  },
  {
    id: "rm-3",
    candidateName: "Emily Johnson",
    interviewAt: "2026-07-19T10:00:00Z",
    offsetLabel: "10 minutes",
    status: "Upcoming",
    channel: "In-app",
  },
  {
    id: "rm-4",
    candidateName: "Marcus Chen",
    interviewAt: "2026-07-20T14:00:00Z",
    offsetLabel: "24 hours",
    status: "Upcoming",
    channel: "Email",
  },
];

export const MOCK_FOLLOWUPS: FollowUpRule[] = [
  {
    id: "fu-1",
    candidateName: "Marcus Chen",
    stage: "Interview Invitation Sent",
    daysWaiting: 3,
    status: "Reminder Sent",
    nextAction: "Wait 4 more days; mark inactive if no reply",
    timeline: [
      { at: "Day 0", label: "Invitation sent" },
      { at: "Day 3", label: "No reply — reminder generated" },
      { at: "Day 7", label: "Mark inactive if still silent" },
    ],
  },
  {
    id: "fu-2",
    candidateName: "Sofia Alvarez",
    stage: "Interview Invitation Sent",
    daysWaiting: 1,
    status: "Monitoring",
    nextAction: "Check again in 2 days",
    timeline: [
      { at: "Day 0", label: "Invitation sent" },
      { at: "Day 3", label: "Send reminder if no reply" },
    ],
  },
  {
    id: "fu-3",
    candidateName: "Noah Williams",
    stage: "Follow-up exhausted",
    daysWaiting: 7,
    status: "Inactive",
    nextAction: "Notify recruiter — candidate inactive",
    timeline: [
      { at: "Day 0", label: "Invitation sent" },
      { at: "Day 3", label: "Reminder sent" },
      { at: "Day 7", label: "Marked inactive" },
    ],
  },
];

export const MOCK_SCHEDULES: ScheduleSuggestion[] = [
  {
    id: "sch-1",
    candidateName: "Emily Johnson",
    slot: {
      id: "slot-a",
      day: "Saturday",
      date: "Jul 19, 2026",
      time: "10:00 AM",
      duration: "45 min",
      timezone: "UTC+6:30",
      available: true,
    },
    meetLink: "https://meet.google.com/abc-defg-hij",
    recruiterAvailable: true,
    candidateAvailable: true,
    confirmed: false,
  },
  {
    id: "sch-2",
    candidateName: "Marcus Chen",
    slot: {
      id: "slot-b",
      day: "Sunday",
      date: "Jul 20, 2026",
      time: "2:00 PM",
      duration: "45 min",
      timezone: "UTC+6:30",
      available: true,
    },
    meetLink: "https://meet.google.com/xyz-uvwx-yz",
    recruiterAvailable: true,
    candidateAvailable: true,
    confirmed: true,
  },
];

export const MOCK_EVALUATIONS: InterviewEvaluationResult[] = [
  {
    id: "ev-1",
    candidateId: "c1",
    candidateName: "Emily Johnson",
    summary:
      "Strong frontend fundamentals with clear communication. Demonstrated solid React patterns and thoughtful UI trade-offs.",
    strengths: ["React/TypeScript depth", "Clear explanations", "Product sense"],
    weaknesses: ["Limited system design exposure", "Light testing discussion"],
    communication: 91,
    technical: 88,
    cultureFit: 90,
    confidence: 0.87,
    recommendation: "Highly Recommended",
    notes: "Advance to final round.",
  },
  {
    id: "ev-2",
    candidateId: "c2",
    candidateName: "Marcus Chen",
    summary:
      "Capable engineer with good architecture instincts. Communication was solid; culture fit looks positive.",
    strengths: ["Problem solving", "Component architecture"],
    weaknesses: ["Slightly above budget", "Could deepen Tailwind craft"],
    communication: 84,
    technical: 86,
    cultureFit: 82,
    confidence: 0.78,
    recommendation: "Recommended",
    notes: "Strong backup hire.",
  },
];

export const MOCK_OFFERS: OfferLetter[] = [
  {
    id: "of-1",
    candidateId: "c1",
    candidateName: "Emily Johnson",
    role: "Junior Frontend Developer",
    salarySummary: "Competitive monthly package within approved budget band",
    benefits: [
      "Health insurance",
      "Hybrid work (3 remote days)",
      "Learning stipend",
      "18 days annual leave",
    ],
    joiningDate: "August 4, 2026",
    companyIntro:
      "TalentPilot Labs builds autonomous multi-agent systems that help HR teams hire with clarity and speed.",
    onboarding: [
      "Complete IT access setup",
      "Meet your buddy and manager",
      "Review handbook & code of conduct",
      "Ship first starter ticket in week 1",
    ],
    letterBody: `Dear Emily Johnson,\n\nWe are delighted to offer you the position of Junior Frontend Developer at TalentPilot Labs.\n\nJoining date: August 4, 2026.\n\nCompensation details will be shared in a secure offer pack. Please do not share sensitive terms externally.\n\nWe look forward to welcoming you.\n\nWarm regards,\nPeople Team`,
    status: "Draft",
  },
];

export const MOCK_ACTIVITY: ActivityEvent[] = [
  {
    id: "act-1",
    time: "09:20",
    title: "Resume Received",
    description: "Emily Johnson submitted application",
    agent: "Master Recruitment Agent",
    status: "success",
  },
  {
    id: "act-2",
    time: "09:21",
    title: "Acknowledgement Email Sent",
    description: "Candidate Communication Agent",
    agent: "Candidate Communication Agent",
    status: "success",
  },
  {
    id: "act-3",
    time: "09:30",
    title: "Resume Screened",
    description: "Skills and experience extracted",
    agent: "Resume Parser Agent",
    status: "success",
  },
  {
    id: "act-4",
    time: "09:35",
    title: "Candidate Ranked",
    description: "Match score 96% — Highly Recommended",
    agent: "Candidate Matching Agent",
    status: "success",
  },
  {
    id: "act-5",
    time: "10:10",
    title: "Interview Scheduled",
    description: "Sat Jul 19 · 10:00 AM",
    agent: "Interview Scheduling Agent",
    status: "success",
  },
  {
    id: "act-6",
    time: "10:12",
    title: "Invitation Sent",
    description: "Interview email delivered",
    agent: "Candidate Communication Agent",
    status: "success",
  },
  {
    id: "act-7",
    time: "Tomorrow",
    title: "Reminder Scheduled",
    description: "24h / 1h / 10m reminders queued",
    agent: "Interview Reminder Agent",
    status: "scheduled",
  },
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: "n1",
    title: "Email sent",
    message: "Acknowledgement email delivered to Emily Johnson",
    type: "success",
    read: false,
    createdAt: "2026-07-18T09:21:00Z",
  },
  {
    id: "n2",
    title: "Upcoming interview",
    message: "Emily Johnson — tomorrow at 10:00 AM",
    type: "info",
    read: false,
    createdAt: "2026-07-18T10:12:00Z",
  },
  {
    id: "n3",
    title: "Follow-up needed",
    message: "Marcus Chen has not replied in 3 days",
    type: "warning",
    read: false,
    createdAt: "2026-07-18T11:00:00Z",
  },
  {
    id: "n4",
    title: "Delivery failed",
    message: "Reminder to Noah Williams bounced",
    type: "error",
    read: true,
    createdAt: "2026-07-17T16:00:00Z",
  },
];

export const MOCK_AUTOMATION_STATS: AutomationStats = {
  emailsSentToday: 12,
  pendingFollowUps: 3,
  upcomingInterviews: 4,
  candidatesWaiting: 5,
  offerLettersSent: 1,
  automationSuccessRate: 96,
};

export const AUTOMATION_PIPELINE: AutomationAgent[] = [
  {
    id: "app-submitted",
    label: "Application Submitted",
    description: "Candidate enters the funnel",
    status: "completed",
    progress: 100,
  },
  {
    id: "comm",
    label: "Candidate Communication",
    description: "Acknowledgement & outreach emails",
    status: "completed",
    progress: 100,
  },
  {
    id: "screening",
    label: "Resume Screening",
    description: "Parse and extract profile",
    status: "completed",
    progress: 100,
  },
  {
    id: "matching",
    label: "Candidate Matching",
    description: "Score and rank candidates",
    status: "completed",
    progress: 100,
  },
  {
    id: "scheduling",
    label: "Interview Scheduling",
    description: "Find mutual availability",
    status: "completed",
    progress: 100,
  },
  {
    id: "reminder",
    label: "Interview Reminder",
    description: "24h / 1h / 10m reminders",
    status: "running",
    progress: 60,
  },
  {
    id: "evaluation",
    label: "Interview Evaluation",
    description: "Summarize interviewer notes",
    status: "pending",
    progress: 0,
  },
  {
    id: "hr-decision",
    label: "HR Final Decision",
    description: "Recruiter approves or rejects",
    status: "pending",
    progress: 0,
  },
  {
    id: "offer",
    label: "Offer Letter",
    description: "Generate and send offer",
    status: "pending",
    progress: 0,
  },
  {
    id: "followup",
    label: "Candidate Follow-up",
    description: "Monitor replies and inactivity",
    status: "pending",
    progress: 0,
  },
  {
    id: "complete",
    label: "Recruitment Completed",
    description: "Pipeline closed",
    status: "pending",
    progress: 0,
  },
];
