import { motion } from 'framer-motion'
import { Copy, Download, LoaderCircle, Send } from 'lucide-react'
import { useEffect, useState } from 'react'
import { AppShell } from '../../components/AppShell'
import { PageHeader } from '../../components/PageHeader'
import { StatusBadge } from '../../components/StatusBadge'
import { TimelineList } from '../../components/TimelineList'
import {
  generateEmail,
  listEmails,
  sendEmail,
  updateEmail,
} from '../../services/automation/communication'
import type { CandidateEmail, CommunicationEvent } from '../../types/automation'

const events: CommunicationEvent[] = [
  'Resume Received',
  'Interview Invitation',
  'Interview Completed',
  'Selected',
  'Rejected',
]

export function CommunicationPage() {
  const [emails, setEmails] = useState<CandidateEmail[]>([])
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [event, setEvent] = useState<CommunicationEvent>('Resume Received')
  const [name, setName] = useState('New Candidate')
  const [notice, setNotice] = useState<string | null>(null)

  useEffect(() => {
    void listEmails().then((data) => {
      setEmails(data)
      setSelectedId(data[0]?.id ?? null)
      setLoading(false)
    })
  }, [])

  const selected = emails.find((email) => email.id === selectedId) ?? null

  async function onGenerate() {
    const draft = await generateEmail(name, event)
    setEmails((prev) => [draft, ...prev])
    setSelectedId(draft.id)
    setNotice('Draft generated by Communication Agent.')
  }

  async function onSave() {
    if (!selected) return
    const updated = await updateEmail(selected.id, {
      subject: selected.subject,
      body: selected.body,
    })
    if (!updated) return
    setEmails((prev) => prev.map((email) => (email.id === updated.id ? updated : email)))
    setNotice('Draft saved.')
  }

  async function onSend() {
    if (!selected) return
    const updated = await sendEmail(selected.id)
    if (!updated) return
    setEmails((prev) => prev.map((email) => (email.id === updated.id ? updated : email)))
    setNotice('Email marked as Sent.')
  }

  async function onCopy() {
    if (!selected) return
    await navigator.clipboard.writeText(`${selected.subject}\n\n${selected.body}`)
    setNotice('Copied to clipboard.')
  }

  function onDownload() {
    if (!selected) return
    const blob = new Blob([`${selected.subject}\n\n${selected.body}`], {
      type: 'text/plain',
    })
    const url = URL.createObjectURL(blob)
    const anchor = document.createElement('a')
    anchor.href = url
    anchor.download = `${selected.candidateName.replace(/\s+/g, '-').toLowerCase()}-email.txt`
    anchor.click()
    URL.revokeObjectURL(url)
    setNotice('Download started.')
  }

  return (
    <AppShell title="Candidate Communication">
      <PageHeader
        eyebrow="Automation"
        title="Candidate Communication Agent"
        description="Generate, preview, edit, and send recruitment emails for every hiring event."
      />

      <div className="auto-toolbar glass-panel">
        <label>
          Candidate
          <input value={name} onChange={(e) => setName(e.target.value)} />
        </label>
        <label>
          Event
          <select value={event} onChange={(e) => setEvent(e.target.value as CommunicationEvent)}>
            {events.map((item) => (
              <option key={item} value={item}>
                {item}
              </option>
            ))}
          </select>
        </label>
        <button type="button" className="btn btn--primary" onClick={() => void onGenerate()}>
          Generate email
        </button>
      </div>

      {notice ? <p className="inline-notice">{notice}</p> : null}

      {loading ? (
        <p className="state-line">
          <LoaderCircle className="spin" size={16} /> Loading communications…
        </p>
      ) : (
        <div className="auto-split">
          <section className="glass-panel">
            <h2>Email timeline</h2>
            <div className="stack-list">
              {emails.map((email) => (
                <button
                  key={email.id}
                  type="button"
                  className={`stack-item${email.id === selectedId ? ' is-active' : ''}`}
                  onClick={() => setSelectedId(email.id)}
                >
                  <div className="stack-item__top">
                    <strong>{email.candidateName}</strong>
                    <StatusBadge status={email.status} />
                  </div>
                  <p>{email.event}</p>
                  <span>{email.createdAt}</span>
                </button>
              ))}
            </div>
          </section>

          <section className="glass-panel">
            {selected ? (
              <motion.div
                key={selected.id}
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
              >
                <div className="editor-head">
                  <div>
                    <h2>Preview & edit</h2>
                    <p className="muted-line">
                      {selected.event} · {selected.candidateName}
                    </p>
                  </div>
                  <StatusBadge status={selected.status} />
                </div>

                <label className="field">
                  Subject
                  <input
                    value={selected.subject}
                    onChange={(e) =>
                      setEmails((prev) =>
                        prev.map((email) =>
                          email.id === selected.id
                            ? { ...email, subject: e.target.value }
                            : email,
                        ),
                      )
                    }
                  />
                </label>

                <label className="field">
                  Body
                  <textarea
                    rows={12}
                    value={selected.body}
                    onChange={(e) =>
                      setEmails((prev) =>
                        prev.map((email) =>
                          email.id === selected.id ? { ...email, body: e.target.value } : email,
                        ),
                      )
                    }
                  />
                </label>

                <div className="cta-row">
                  <button type="button" className="btn btn--primary" onClick={() => void onSave()}>
                    Save edits
                  </button>
                  <button type="button" className="btn btn--ghost" onClick={() => void onCopy()}>
                    <Copy size={15} /> Copy
                  </button>
                  <button type="button" className="btn btn--ghost" onClick={onDownload}>
                    <Download size={15} /> Download
                  </button>
                  <button type="button" className="btn btn--primary" onClick={() => void onSend()}>
                    <Send size={15} /> Send
                  </button>
                </div>
              </motion.div>
            ) : (
              <p className="muted-line">Select an email to preview.</p>
            )}
          </section>

          <section className="glass-panel">
            <h2>History</h2>
            <TimelineList
              items={emails.map((email) => ({
                id: email.id,
                title: email.subject,
                detail: `${email.event} · ${email.candidateName}`,
                at: email.createdAt,
                status: email.status,
                agent: 'Communication',
              }))}
            />
          </section>
        </div>
      )}
    </AppShell>
  )
}
